import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor config — wraps the SAME Vite build (`dist/`) as the web app into a native
 * iOS/iPadOS app (WKWebView + native plugins: push, geolocation, haptics, share, motion).
 * Build steps: docs/IOS.md. The native `ios/` project is generated by `npx cap add ios`
 * (needs Xcode + CocoaPods) and is git-ignored — regenerate it, don't commit it.
 */
const config: CapacitorConfig = {
  appId: 'com.kunalbhatia.brahmaand',
  appName: 'Brahmaand',
  webDir: 'dist',
  ios: {
    contentInset: 'never', // we manage safe-area insets in CSS
    backgroundColor: '#000000',
  },
  server: {
    // during native development you can point this at the live dev server for hot reload:
    // url: 'http://<your-mac-LAN-ip>:5173', cleartext: true,
  },
};

export default config;
